### ISSUE TITLE
Require issues (browserify)

### ISSUE THREAD

**Issue by astro** [iriscouch/browser-request#5]
Hi

Thanks for this convenient library that allows me to use a single codebase on browser & node! I'm using this with browserify, but I've had to remove a few things from `request.js`:
- `require('./xmlhttprequest')` — that file is not in the current directory
- The check for `XHR.name !== 'cXMLHttpRequest'`
- I also added a `browserify` key to `package.json`. A `main` key would help as well here.

Do you understand the issues or do you want me to draft a pull request?

**Comment by jhs** [comment]
Hi, if I understand correctly, you are running browserify on browser-only software. browser-request does not run on Node.js and is not intended for browserify.

Please correct me if I am wrong.

**Comment by astro** [comment]
It's just browserify itself that runs on node. It bundles up all the source files and dependency libraries for static delivery to browsers. In those source files I need to perform AJAX and I very much like to stick to the request syntax, which browser-request provides for me.

**Comment by jhs** [comment]
Thanks for the follow-up. You like the request syntax so I assume you have a good head on your shoulders.

I must misunderstand browserify somewhat then. I never expected browser-request to be processed by it.

In this case, can I impose on you to send a pull request? I am not using browserify myself so I may be unclear on the correct steps. It sounds exciting though because I have been a little frustrated with Ender (which is the only reason package.json and the Node stuff exists at present.)

Thanks again!

**Comment by astro** [comment]
Hi

My [fork](https://github.com/astro/browser-request) does now contain what's necessary for usage with browserify. I fear you can't merge it while sustaining compatibility to Ender/RequireJS?

If there's no way these both environments could go together I'm going to push my fork to npm as browserify-request.

**Comment by jhs** [comment]
Thanks. I am looking at it now. I think we can merge these.

The core idea is that browser-request is one, simple CommonJS module. That's it. So it should be browserify-able.

To build it for various platforms, I apply a (worryingly) complex set of wrappers, for example for traditional browser mode, the CommonJS is evaluated with `window` in the place of `module.exports`.

This gets slightly tricky because XMLHttpRequest is an external project, not in NPM, and its license is LGPL. Therefore I want to use it completely unmodified. (I'm starting to think that's overkill.) This component is **not** CommonJS so it needs its own wrappers, etc.

Anyway, the point is I am comfortable with build-time complexity so I would like to merge your work in. @mikeal has also expressed interest in merging this project into the "official" request so it is worth our while to get it all working well.

**Comment by jhs** [comment]
Your fork looks good, I've merged it to a branch. Would you help me understand the best way to make it all work? Thanks!

Your browser-request usage is one component in a larger project? Would it make sense to build a completely browserified module that was _only_ browser-request, or is that not the point?

I think the answer "no", and your workflow is this:
1. Depend on browser-request in your Node app. `npm install it`
2. `require()` it from your code
3. Attempt to browserify that code and publish the output.

Is that correct? I'm hoping to better understand your requirements/workflow so you (and other "you"s) get what you need with no hassle.

**Comment by astro** [comment]
Right, I'm using `require('browser-request')` and run browserify myself. Even more so, I'm building another library (node-xmpp) that final users will just require with browserify.

♥ for merging it with the node.js request project. I think proper stream support is still missing for this one, no?

BTW, you don't need node_modules in git if they can be installed via npm.

**Comment by jhs** [comment]
Thanks for your patience. I believe I have a very good solution. It is nearly ready.

The key point is that the Ender build is already exactly what browserify needs. (Note, the ender build is not _made_ with Ender, it is simply formatted how Ender likes: 100% CommonJS. That is what browserify wants too and frankly I am very happy to make browserify a first among equals when it comes to building client bundles.

I expect to wrap this up and push a branch in about 1 hour.

**Comment by jhs** [comment]
Ok, I published a new release to NPM. I have confirmed that it works with browserify, and I documented how I used it based on your technique in the README.

**Comment by astro** [comment]
Works for me perfectly. Thank you!
